export const realPlayers = [
  {id:"haaland",name:"Erling Haaland",aliases:["Haaland"],position:"striker",country:"Norway",club:"Manchester City",number:9,honour:"the Premier League"},
  {id:"foden",name:"Phil Foden",aliases:["Foden"],position:"midfielder",country:"England",club:"Manchester City",number:47,honour:"the Premier League"},
  {id:"saka",name:"Bukayo Saka",aliases:["Saka"],position:"winger",country:"England",club:"Arsenal",number:7,honour:"the Premier League"},
  {id:"rice",name:"Declan Rice",aliases:["Rice"],position:"midfielder",country:"England",club:"Arsenal",number:41,honour:"the Premier League"},
  {id:"palmer",name:"Cole Palmer",aliases:["Palmer"],position:"attacking midfielder",country:"England",club:"Chelsea",number:10,honour:"the UEFA Conference League"},
  {id:"maddison",name:"James Maddison",aliases:["Maddison"],position:"midfielder",country:"England",club:"Tottenham Hotspur",number:10,honour:"the UEFA Conference League"},
  {id:"mbappe",name:"Kylian Mbappe",aliases:["Mbappe"],position:"forward",country:"France",club:"Real Madrid",number:10,honour:"the FIFA World Cup"},
  {id:"bellingham",name:"Jude Bellingham",aliases:["Bellingham"],position:"midfielder",country:"England",club:"Real Madrid",number:5,honour:"the UEFA Champions League"},
  {id:"vinicius",name:"Vinicius Junior",aliases:["Vinicius","Vini Jr","Vini"],position:"winger",country:"Brazil",club:"Real Madrid",number:7,honour:"the UEFA Champions League"},
  {id:"yamal",name:"Lamine Yamal",aliases:["Yamal"],position:"winger",country:"Spain",club:"Barcelona",number:10,honour:"La Liga"},
  {id:"kane",name:"Harry Kane",aliases:["Kane"],position:"striker",country:"England",club:"Bayern Munich",number:9,honour:"the Bundesliga"},
  {id:"musiala",name:"Jamal Musiala",aliases:["Musiala"],position:"attacking midfielder",country:"Germany",club:"Bayern Munich",number:10,honour:"the Bundesliga"},
  {id:"dembele",name:"Ousmane Dembele",aliases:["Dembele"],position:"forward",country:"France",club:"Paris Saint-Germain",number:10,honour:"the UEFA Champions League"},
  {id:"kvara",name:"Khvicha Kvaratskhelia",aliases:["Kvaratskhelia","Kvara"],position:"winger",country:"Georgia",club:"Paris Saint-Germain",number:7,honour:"the Ligue 1 title"},
  {id:"leao",name:"Rafael Leao",aliases:["Leao"],position:"winger",country:"Portugal",club:"AC Milan",number:10,honour:"Serie A"},
  {id:"pulisic",name:"Christian Pulisic",aliases:["Pulisic"],position:"winger",country:"United States",club:"AC Milan",number:11,honour:"the UEFA Champions League"},
  {id:"lautaro",name:"Lautaro Martinez",aliases:["Lautaro","Martinez"],position:"striker",country:"Argentina",club:"Inter Milan",number:10,honour:"Serie A"},
  {id:"yildiz",name:"Kenan Yildiz",aliases:["Yildiz"],position:"forward",country:"Turkey",club:"Juventus",number:10,honour:"the Coppa Italia"},
  {id:"gyokeres",name:"Viktor Gyokeres",aliases:["Gyokeres"],position:"striker",country:"Sweden",club:"Arsenal",number:14,honour:"the Primeira Liga"},
  {id:"modric",name:"Luka Modric",aliases:["Modric"],position:"midfielder",country:"Croatia",club:"AC Milan",number:14,honour:"the UEFA Champions League"},

  {id:"bruno",name:"Bruno Fernandes",aliases:["Bruno"],position:"midfielder",country:"Portugal",club:"Manchester United",number:8,honour:"the UEFA Nations League"},
  {id:"garnacho",name:"Alejandro Garnacho",aliases:["Garnacho"],position:"winger",country:"Argentina",club:"Aston Villa",number:17,honour:"the Copa America"},
  {id:"diallo",name:"Amad Diallo",aliases:["Amad"],position:"winger",country:"Ivory Coast",club:"Manchester United",number:16,honour:"the FA Cup"},
  {id:"martinez",name:"Lisandro Martinez",aliases:["Lisandro Martinez"],position:"defender",country:"Argentina",club:"Manchester United",number:6,honour:"the Copa America"},
  {id:"grealish",name:"Jack Grealish",aliases:["Grealish"],position:"winger",country:"England",club:"Everton",number:10,honour:"the Premier League"},
  {id:"isak",name:"Alexander Isak",aliases:["Isak"],position:"striker",country:"Sweden",club:"Liverpool",number:9,honour:"the Premier League"},
  {id:"salah",name:"Mohamed Salah",aliases:["Salah"],position:"forward",country:"Egypt",club:"Liverpool",number:11,honour:"the Premier League"},
  {id:"van-dijk",name:"Virgil van Dijk",aliases:["Van Dijk","Virgil van Dijk"],position:"defender",country:"Netherlands",club:"Liverpool",number:4,honour:"the Premier League"},
  {id:"wirtz",name:"Florian Wirtz",aliases:["Wirtz"],position:"midfielder",country:"Germany",club:"Liverpool",number:7,honour:"the Bundesliga"},
  {id:"alisson",name:"Alisson Becker",aliases:["Alisson"],position:"goalkeeper",country:"Brazil",club:"Liverpool",number:1,honour:"the Premier League"},
  {id:"szoboszlai",name:"Dominik Szoboszlai",aliases:["Szoboszlai"],position:"midfielder",country:"Hungary",club:"Liverpool",number:8,honour:"the Premier League"},
  {id:"odegaard",name:"Martin Odegaard",aliases:["Odegaard"],position:"midfielder",country:"Norway",club:"Arsenal",number:8,honour:"the Premier League"},
  {id:"saliba",name:"William Saliba",aliases:["Saliba"],position:"defender",country:"France",club:"Arsenal",number:2,honour:"the FIFA World Cup"},
  {id:"havertz",name:"Kai Havertz",aliases:["Havertz"],position:"forward",country:"Germany",club:"Arsenal",number:29,honour:"the UEFA Champions League"},
  {id:"eze",name:"Eberechi Eze",aliases:["Eze"],position:"attacking midfielder",country:"England",club:"Arsenal",number:10,honour:"the FA Cup"},
  {id:"madueke",name:"Noni Madueke",aliases:["Madueke"],position:"winger",country:"England",club:"Arsenal",number:20,honour:"the FA Cup"},
  {id:"branthwaite",name:"Jarrad Branthwaite",aliases:["Branthwaite"],position:"defender",country:"England",club:"Everton",number:32,honour:"the FA Youth Cup"},
  {id:"pickford",name:"Jordan Pickford",aliases:["Pickford"],position:"goalkeeper",country:"England",club:"Everton",number:1,honour:"the UEFA European Championship"},
  {id:"iwobi",name:"Alex Iwobi",aliases:["Iwobi"],position:"midfielder",country:"Nigeria",club:"Fulham",number:17,honour:"the FA Cup"},
  {id:"robinson",name:"Antonee Robinson",aliases:["Robinson"],position:"defender",country:"United States",club:"Fulham",number:33,honour:"the CONCACAF Nations League"},
  {id:"mitoma",name:"Kaoru Mitoma",aliases:["Mitoma"],position:"winger",country:"Japan",club:"Brighton",number:22,honour:"the J.League Cup"},
  {id:"ferguson",name:"Evan Ferguson",aliases:["Ferguson"],position:"striker",country:"Ireland",club:"Brighton",number:28,honour:"the UEFA Europa Conference League"},
  {id:"gibbs-white",name:"Morgan Gibbs-White",aliases:["Gibbs-White"],position:"midfielder",country:"England",club:"Nottingham Forest",number:10,honour:"the UEFA Europa Conference League"},
  {id:"hudson-odoi",name:"Callum Hudson-Odoi",aliases:["Hudson-Odoi","CHO"],position:"winger",country:"England",club:"Nottingham Forest",number:14,honour:"the UEFA Champions League"},
  {id:"kudus",name:"Mohammed Kudus",aliases:["Kudus"],position:"midfielder",country:"Ghana",club:"Tottenham Hotspur",number:20,honour:"the UEFA Europa Conference League"},
  {id:"kulusevski",name:"Dejan Kulusevski",aliases:["Kulusevski"],position:"winger",country:"Sweden",club:"Tottenham Hotspur",number:21,honour:"the FA Cup"},
  {id:"marmoush",name:"Omar Marmoush",aliases:["Marmoush"],position:"forward",country:"Egypt",club:"Manchester City",number:7,honour:"the DFB-Pokal"},
  {id:"doku",name:"Jeremy Doku",aliases:["Doku"],position:"winger",country:"Belgium",club:"Manchester City",number:11,honour:"the Premier League"},
  {id:"donnarumma",name:"Gianluigi Donnarumma",aliases:["Donnarumma"],position:"goalkeeper",country:"Italy",club:"Manchester City",number:25,honour:"the UEFA Champions League"},
  {id:"gavi",name:"Gavi",aliases:["Gavi"],position:"midfielder",country:"Spain",club:"Barcelona",number:6,honour:"La Liga"},
  {id:"pedri",name:"Pedri",aliases:["Pedri"],position:"midfielder",country:"Spain",club:"Barcelona",number:8,honour:"La Liga"},
  {id:"raphinha",name:"Raphinha",aliases:["Raphinha"],position:"winger",country:"Brazil",club:"Barcelona",number:11,honour:"La Liga"},
  {id:"araujo",name:"Ronald Araujo",aliases:["Araujo"],position:"defender",country:"Uruguay",club:"Barcelona",number:4,honour:"La Liga"},
  {id:"lewandowski",name:"Robert Lewandowski",aliases:["Lewandowski"],position:"striker",country:"Poland",club:"Barcelona",number:9,honour:"La Liga"},
  {id:"courtois",name:"Thibaut Courtois",aliases:["Courtois"],position:"goalkeeper",country:"Belgium",club:"Real Madrid",number:1,honour:"the UEFA Champions League"},
  {id:"rodrygo",name:"Rodrygo",aliases:["Rodrygo"],position:"forward",country:"Brazil",club:"Real Madrid",number:11,honour:"the UEFA Champions League"},
  {id:"valverde",name:"Federico Valverde",aliases:["Valverde"],position:"midfielder",country:"Uruguay",club:"Real Madrid",number:8,honour:"the UEFA Champions League"},
  {id:"griezmann",name:"Antoine Griezmann",aliases:["Griezmann"],position:"forward",country:"France",club:"Atletico Madrid",number:7,honour:"the UEFA Europa League"},
  {id:"alvarez",name:"Julian Alvarez",aliases:["Alvarez"],position:"striker",country:"Argentina",club:"Atletico Madrid",number:19,honour:"the FIFA World Cup"},
  {id:"morata",name:"Alvaro Morata",aliases:["Morata"],position:"striker",country:"Spain",club:"Galatasaray",number:7,honour:"the UEFA Champions League"},
  {id:"kimmich",name:"Joshua Kimmich",aliases:["Kimmich"],position:"midfielder",country:"Germany",club:"Bayern Munich",number:6,honour:"the Bundesliga"},
  {id:"neuer",name:"Manuel Neuer",aliases:["Neuer"],position:"goalkeeper",country:"Germany",club:"Bayern Munich",number:1,honour:"the Bundesliga"},
  {id:"olise",name:"Michael Olise",aliases:["Olise"],position:"winger",country:"France",club:"Bayern Munich",number:17,honour:"the Bundesliga"},
  {id:"goretzka",name:"Leon Goretzka",aliases:["Goretzka"],position:"midfielder",country:"Germany",club:"Bayern Munich",number:8,honour:"the Bundesliga"},
  {id:"upamecano",name:"Dayot Upamecano",aliases:["Upamecano"],position:"defender",country:"France",club:"Bayern Munich",number:2,honour:"the Bundesliga"},
  {id:"tah",name:"Jonathan Tah",aliases:["Tah"],position:"defender",country:"Germany",club:"Bayern Munich",number:4,honour:"the Bundesliga"},
  {id:"kolo-muani",name:"Randal Kolo Muani",aliases:["Kolo Muani"],position:"forward",country:"France",club:"Juventus",number:20,honour:"the UEFA Nations League"},
  {id:"vlahovic",name:"Dusan Vlahovic",aliases:["Vlahovic"],position:"striker",country:"Serbia",club:"Juventus",number:9,honour:"the Coppa Italia"},
  {id:"bremer",name:"Bremer",aliases:["Bremer"],position:"defender",country:"Brazil",club:"Juventus",number:3,honour:"the Coppa Italia"},
  {id:"barella",name:"Nicolo Barella",aliases:["Barella"],position:"midfielder",country:"Italy",club:"Inter Milan",number:23,honour:"Serie A"},
  {id:"bastoni",name:"Alessandro Bastoni",aliases:["Bastoni"],position:"defender",country:"Italy",club:"Inter Milan",number:95,honour:"Serie A"},
  {id:"dimarco",name:"Federico Dimarco",aliases:["Dimarco"],position:"defender",country:"Italy",club:"Inter Milan",number:32,honour:"Serie A"},
  {id:"dovbyk",name:"Artem Dovbyk",aliases:["Dovbyk"],position:"striker",country:"Ukraine",club:"Roma",number:9,honour:"La Liga"},
  {id:"de-bruyne",name:"Kevin De Bruyne",aliases:["De Bruyne","KDB"],position:"midfielder",country:"Belgium",club:"Napoli",number:11,honour:"the Premier League"},
  {id:"lookman",name:"Ademola Lookman",aliases:["Lookman"],position:"forward",country:"Nigeria",club:"Atalanta",number:11,honour:"the UEFA Europa League"},
  {id:"hakimi",name:"Achraf Hakimi",aliases:["Hakimi"],position:"defender",country:"Morocco",club:"Paris Saint-Germain",number:2,honour:"the UEFA Champions League"},
  {id:"vitinha",name:"Vitinha",aliases:["Vitinha"],position:"midfielder",country:"Portugal",club:"Paris Saint-Germain",number:17,honour:"the UEFA Champions League"},
  {id:"marquinhos",name:"Marquinhos",aliases:["Marquinhos"],position:"defender",country:"Brazil",club:"Paris Saint-Germain",number:5,honour:"the UEFA Champions League"},
  {id:"barcola",name:"Bradley Barcola",aliases:["Barcola"],position:"winger",country:"France",club:"Paris Saint-Germain",number:29,honour:"the UEFA Champions League"},
  {id:"lucas-hernandez",name:"Lucas Hernandez",aliases:["Lucas Hernandez"],position:"defender",country:"France",club:"Paris Saint-Germain",number:21,honour:"the FIFA World Cup"},
  {id:"maignan",name:"Mike Maignan",aliases:["Maignan"],position:"goalkeeper",country:"France",club:"AC Milan",number:16,honour:"Serie A"},
  {id:"hernandez",name:"Theo Hernandez",aliases:["Theo Hernandez"],position:"defender",country:"France",club:"Al Hilal",number:19,honour:"Serie A"},
  {id:"reijnders",name:"Tijjani Reijnders",aliases:["Reijnders"],position:"midfielder",country:"Netherlands",club:"Manchester City",number:4,honour:"Serie A"}
];;
